services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=helloworld
      - POSTGRES_DB=sample
    ports:
      - "5432:5432"
    restart: always
