packages:
  - apps/*
  - modules/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - esbuild
  - lefthook
  - nestjs-pino
  - prisma
  - unrs-resolver
